### ISSUE TITLE
JWEDecryptionFailed: decryption operation failed

### ISSUE THREAD

**Issue by tobychidi** [Hebilicious/authjs-nuxt#105]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.7.5
- Builder:          -
- User Config:      devtools, modules, ui, alias, runtimeConfig
- Runtime Modules:  @nuxt/ui@2.8.1, @hebilicious/authjs-nuxt@0.3.0, vue-email/nuxt
- Build Modules:    -

### Reproduction

none

### Describe the bug

[auth][error][JWTSessionError]: Read more at https://errors.authjs.dev#jwtsessionerror

When ever I run the dev server. It worked initially now I get this error. Cannot figure out what we are doing wrong.

### Additional context

```
JWEDecryptionFailed: decryption operation failed
    at gcmDecrypt (file:///C:/Users/tobychidi/Documents/GitHub/wissenschaft/wilventory/node_modules/.pnpm/jose@4.14.6/node_modules/jose/dist/node/esm/runtime/decrypt.js:65:15)
    at decrypt (file:///C:/Users/tobychidi/Documents/GitHub/wissenschaft/wilventory/node_modules/.pnpm/jose@4.14.6/node_modules/jose/dist/node/esm/runtime/decrypt.js:90:20)
    at flattenedDecrypt (file:///C:/Users/tobychidi/Documents/GitHub/wissenschaft/wilventory/node_modules/.pnpm/jose@4.14.6/node_modules/jose/dist/node/esm/jwe/flattened/decrypt.js:140:27)
    at async compactDecrypt (file:///C:/Users/tobychidi/Documents/GitHub/wissenschaft/wilventory/node_modules/.pnpm/jose@4.14.6/node_modules/jose/dist/node/esm/jwe/compact/decrypt.js:15:23)
    at async jwtDecrypt (file:///C:/Users/tobychidi/Documents/GitHub/wissenschaft/wilventory/node_modules/.pnpm/jose@4.14.6/node_modules/jose/dist/node/esm/jwt/decrypt.js:5:23)
    at async Object.decode (file:///C:/Users/tobychidi/Documents/GitHub/wissenschaft/wilventory/node_modules/.pnpm/@auth+core@0.14.0/node_modules/@auth/core/jwt.js:62:25)
    at async Module.session (file:///C:/Users/tobychidi/Documents/GitHub/wissenschaft/wilventory/node_modules/.pnpm/@auth+core@0.14.0/node_modules/@auth/core/lib/routes/session.js:17:34)
    at async AuthInternal (file:///C:/Users/tobychidi/Documents/GitHub/wissenschaft/wilventory/node_modules/.pnpm/@auth+core@0.14.0/node_modules/@auth/core/lib/index.js:29:33)
    at async Auth (file:///C:/Users/tobychidi/Documents/GitHub/wissenschaft/wilventory/node_modules/.pnpm/@auth+core@0.14.0/node_modules/@auth/core/index.js:100:30)
    at <anonymous> (C:\Users\tobychidi\Documents\GitHub\wissenschaft\wilventory\node_modules\.pnpm\@hebilicious+authjs-nuxt@0.3.0_@auth+core@0.14.0_nuxt@3.7.3\node_modules\@hebilicious\authjs-nuxt\dist\runtime\lib\server.mjs:23:22)
```

**Comment by Hebilicious** [comment]
Hi @tobychidi , please post a minimal reproduction.

**Comment by tobychidi** [comment]
I fixed this by clearing the browser storage (cookies and Local storage) whenever changing the NEXTAUTH_SECRET

**Comment by tobychidi** [comment]
I fixed this by clearing the browser storage (cookies and Local storage) whenever changing the NEXTAUTH_SECRET
