### ISSUE TITLE
crypto.getHashes is not implemented yet - CF Workers

### ISSUE THREAD

**Issue by cliqer** [Hebilicious/authjs-nuxt#132]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.1.0`
- Nuxt Version:     `3.8.1`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.2`
- Package Manager:  `bun@1.0.8`
- Builder:          `-`
- User Config:      `nitro`, `experimental`, `sourcemap`, `ssr`, `routeRules`, `modules`, `colorMode`, `alias`, `authJs`, `runtimeConfig`, `tailwindcss`, `viewport`, `security`, `robots`, `gtag`, `pwa`, `app`, `vite`, `devtools`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.9.4`, `nuxt-icon@0.6.5`, `@nuxtjs/robots@3.0.0`, `@nuxtjs/color-mode@3.3.0`, `@hebilicious/authjs-nuxt@0.3.5`, `@nuxt/devtools@1.0.0`, `@kevinmarrec/nuxt-pwa@0.17.0`, `@vueuse/nuxt@10.5.0`, `nuxt-gtag@1.1.1`, `nuxt-security@1.0.0-rc.3`, `nuxt-schema-org@3.1.3`, `nuxt-viewport@2.0.6`, `nuxt-headlessui@1.1.4`
- Build Modules:    `-`

### Reproduction

-

### Describe the bug

Building for Cloudflare Workers using latest Wrangler 3.15.0 throws this error.
Using bun but also tried with pnpm and yarn.

### Logs

```sh
✘ [ERROR] A request to the Cloudflare API (/accounts/7864dd4840d541ed05706c95ca7d412e/workers/scripts/production-test) failed.

  Uncaught Error: [unenv] crypto.getHashes is not implemented yet!
    at worker.js:7768:15 in createNotImplementedError2
    at worker.js:7777:17 in Object.assign.__unenv__
    at worker.js:9042:40 in ./node_modules/.pnpm/object-hash@3.0.0/node_modules/object-hash/index.js
    at worker.js:10162:26 in __webpack_require__
    at worker.js:10305:120
    at worker.js:13153:13
    at worker.js:13154:11
    at worker.js:13155:8 in requireJiti
    at worker.js:40910:18 in lib$3
    at worker.js:41618:9
   [code: 10021]
```

**Comment by cliqer** [comment]
It was a nuxt-security issue :/
