### ISSUE TITLE
[auth][error] UnknownAction: Only GET and POST requests are supported.

### ISSUE THREAD

**Issue by Dodje** [Hebilicious/authjs-nuxt#171]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.19.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.0
- Nitro Version:    2.9.4
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      vue, components, alias, nitro, routeRules, css, modules, dayjs, i18n, runtimeConfig, vite, build, typescript
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-rc.5, dayjs-nuxt@2.1.9, @nuxt/test-utils/module@3.12.0, @hebilicious/authjs-nuxt@0.3.5
- Build Modules:    -
------------------------------

### Reproduction

I appologize for no link due to hard work crunch I have..

### Describe the bug

After nuxt update getting an error in console. My guess is that the method `internalRequest` is expecting some request from `getRequestFromEvent`, but this function is trying to use `deprecated` method. 
![image](https://github.com/Hebilicious/authjs-nuxt/assets/25726086/1cbb241e-54b7-41d4-aea1-27d307a5e156)

### Logs

```sh
ERROR  [auth][error] UnknownAction: Only GET and POST requests are supported. .Read more at https://errors.authjs.dev#unknownaction


 ERROR      at toInternalRequest (file:///home/art/work/flydrone-government-frontend/node_modules/@auth/core/lib/utils/web.js:19:19)
    at Auth (file:///home/art/work/flydrone-government-frontend/node_modules/@auth/core/index.js:67:35)
    at Object.handler (/home/art/work/flydrone-government-frontend/node_modules/@hebilicious/authjs-nuxt/dist/runtime/lib/server.mjs:23:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/art/work/flydrone-government-frontend/node_modules/h3/dist/index.mjs:1962:19
    at async Object.callAsync (file:///home/art/work/flydrone-government-frontend/node_modules/unctx/dist/index.mjs:72:16)
    at async Server.toNodeHandle (file:///home/art/work/flydrone-government-frontend/node_modules/h3/dist/index.mjs:2249:7)
```

**Comment by gxanshu** [comment]
Any updates ?

same issue here
