### ISSUE TITLE
Keycloak Cookie not set

### ISSUE THREAD

**Issue by dissy123** [Hebilicious/authjs-nuxt#19]
### Environment

node 18.0.0
nuxt 3.6.1
nitro 2.5.2

### Reproduction

https://github.com/dissy123/authjs-nuxt/tree/main/playgrounds/keycloak

### Describe the bug

No cookies are set when signin with keycloak, in keycloak i get a user session after the login attempt 

![image 1](https://github.com/Hebilicious/authjs-nuxt/assets/5930734/86495e27-a0ed-47c7-bcab-5067adab6d67)

and this is directly after login:

<img width="466" alt="image" src="https://github.com/Hebilicious/authjs-nuxt/assets/5930734/a6508e71-befe-4cb4-ad39-3f9715869da0">

### Logs

In my monorepo i get the following error message:
```sh
montreet:dev: [auth][error][InvalidCheck]: Read more at https://errors.authjs.dev#invalidcheck
montreet:dev: [auth][cause]: InvalidCheck: PKCE code_verifier cookie was missing.
montreet:dev:     at Object.use (file:///Users/matthiasdollfuss/00_Dev/localflow-monorepo/node_modules/.pnpm/@auth+core@0.9.0/node_modules/@auth/core/lib/oauth/checks.js:42:19)
montreet:dev:     at handleOAuth (file:///Users/matthiasdollfuss/00_Dev/localflow-monorepo/node_modules/.pnpm/@auth+core@0.9.0/node_modules/@auth/core/lib/oauth/callback.js:52:44)
montreet:dev:     at async Module.callback (file:///Users/matthiasdollfuss/00_Dev/localflow-monorepo/node_modules/.pnpm/@auth+core@0.9.0/node_modules/@auth/core/lib/routes/callback.js:20:41)
montreet:dev:     at async AuthInternal (file:///Users/matthiasdollfuss/00_Dev/localflow-monorepo/node_modules/.pnpm/@auth+core@0.9.0/node_modules/@auth/core/lib/index.js:65:38)
montreet:dev:     at async Auth (file:///Users/matthiasdollfuss/00_Dev/localflow-monorepo/node_modules/.pnpm/@auth+core@0.9.0/node_modules/@auth/core/index.js:100:30)
montreet:dev:     at async file:///Users/matthiasdollfuss/00_Dev/localflow-monorepo/01_Websites/montreet/.nuxt/dev/index.mjs:745:22
montreet:dev:     at async Object.handler (file:///Users/matthiasdollfuss/00_Dev/localflow-monorepo/node_modules/.pnpm/h3@1.6.6/node_modules/h3/dist/index.mjs:1255:19)
montreet:dev:     at async Server.toNodeHandle (file:///Users/matthiasdollfuss/00_Dev/localflow-monorepo/node_modules/.pnpm/h3@1.6.6/node_modules/h3/dist/index.mjs:1330:7)
montreet:dev: [auth][details]: {
montreet:dev:   "provider": "keycloak"
montreet:dev: }
```

In the reproduction i don't get an error message. 
But the cookies are not set.

**Comment by Hebilicious** [comment]
Hey, Are you able to make it work with authjs directly without this module ? This looks like it could be a provider issue.

**Comment by Hebilicious** [comment]
Fixed by https://github.com/Hebilicious/authjs-nuxt/pull/38, please re-open if this still happens in latest version.
