### ISSUE TITLE
useRuntimeConfig is not defined

### ISSUE THREAD

**Issue by selemondev** [Hebilicious/authjs-nuxt#30]
### Environment

Node version: `18.16.1`

```
{
  "name": "nuxt-auth",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "lint": "eslint --max-warnings 0 .",
    "typecheck": "nuxt typecheck",
    "start": "NODE_ENV=production node .output/server/index.mjs"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/color-mode": "^3.3.0",
    "@nuxtjs/eslint-config-typescript": "^12.0.0",
    "@nuxtjs/google-fonts": "^3.0.1",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@prisma/client": "^5.0.0",
    "@types/bcryptjs": "^2.4.2",
    "@types/node": "^20.4.2",
    "eslint": "^8.45.0",
    "nuxt": "^3.6.3",
    "nuxt-icon": "^0.4.2",
    "prisma": "^5.0.0",
    "typescript": "^5.1.6",
    "vue-tsc": "^1.8.5"
  },
  "dependencies": {
    "@auth/core": "^0.9.0",
    "@auth/prisma-adapter": "^1.0.1",
    "@hebilicious/authjs-nuxt": "^0.1.5",
    "@types/jsonwebtoken": "^9.0.2",
    "@vuelidate/core": "^2.0.3",
    "@vuelidate/validators": "^2.0.3",
    "bcryptjs": "^2.4.3",
    "jsonwebtoken": "^9.0.1"
  }
}
```

### Reproduction

Here is the error that I got in my console: 

```
[nuxt] [request error] [unhandled] [500] useRuntimeConfig is not defined
  at getServerOrigin /.nuxt/dev/index.mjs:842:24` and also at `at getServerToken .nuxt/dev/index.mjs:926:19
```

### Describe the bug

I am trying to get the JWT, I have followed the instruction as written in the docs.

In my `/server/jwt.get.ts` file I have the following code: 

```ts
import { authOptions } from "../api/auth/[...]"
import { getServerSession, getServerToken } from "#auth"
export default defineEventHandler(async (event) => {
  const session = await getServerSession(event, authOptions)
  const jwt = await getServerToken(event, authOptions)
  return { session, jwt }
})
``` 

but I get the following error in my console: 

```
[nuxt] [request error] [unhandled] [500] useRuntimeConfig is not defined  2:34:39 AM
  at getServerOrigin
 ```

 here is the code that I have defined in the `/server/api/auth/[...].ts` file: 

```ts
import GithubProvider from "@auth/core/providers/github";
import GoogleProvider from "@auth/core/providers/google";
import type { AuthConfig } from "@auth/core/types"
import { NuxtAuthHandler } from "#auth";
import { PrismaAdapter } from "@auth/prisma-adapter";
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();
const runtimeConfig = useRuntimeConfig()

export const authOptions: AuthConfig = {
    adapter: PrismaAdapter(prisma),
    secret: 'fghjgsdfjhktrygjndfbvvsdvbtrhgfg',
    providers: [
        GithubProvider({
            clientId: runtimeConfig.GITHUB_CLIENT_ID,
            clientSecret: runtimeConfig.GITHUB_CLIENT_SECRET
        }),

        GoogleProvider({
            clientId: runtimeConfig.GOOGLE_CLIENT_ID,
            clientSecret: runtimeConfig.GOOGLE_CLIENT_SECRET
        })
    ]
}

export default NuxtAuthHandler(authOptions, runtimeConfig) 
```

### Additional context

Here is the error that I got in my console: 
```
[nuxt] [request error] [unhandled] [500] useRuntimeConfig is not defined
  at getServerOrigin /.nuxt/dev/index.mjs:842:24
  ```

### Logs
Here is the error that I got in my console: 
```sh
[nuxt] [request error] [unhandled] [500] useRuntimeConfig is not defined
  at getServerOrigin /.nuxt/dev/index.mjs:842:24` and also at `at getServerToken .nuxt/dev/index.mjs:926:19
```

**Comment by Hebilicious** [comment]
Fixed in https://github.com/Hebilicious/authjs-nuxt/releases/tag/v0.1.6
