### ISSUE TITLE
appendHeader is not a function

### ISSUE THREAD

**Issue by dissy123** [Hebilicious/authjs-nuxt#50]
### Environment

node 18.0.0
pnpm 8.6.1

### Reproduction

https://github.com/dissy123/authjs-nuxt/tree/fix/keycloak

### Describe the bug

appendHeader not found in utils.ts maybe check type?

When I change this line it works:

https://github.com/Hebilicious/authjs-nuxt/commit/de8c9fc5dfdf977a76f61fbbb0fe675e6e1d9d67

Testet only with keycloak provider

### Logs

```sh
playground_keycloak:dev: [nuxt] [request error] [unhandled] [500] event.node.res.appendHeader is not a function
playground_keycloak:dev:   at respondWithResponse (./.nuxt/dev/index.mjs:851:22)  
playground_keycloak:dev:   at ./.nuxt/dev/index.mjs:890:12  
playground_keycloak:dev:   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
playground_keycloak:dev:   at async Object.handler (/Users/matthiasdollfuss/00_Dev/authjs-nuxt-new/node_modules/.pnpm/h3@1.7.1/node_modules/h3/dist/index.mjs:1284:19)  
playground_keycloak:dev:   at async Server.toNodeHandle (/Users/matthiasdollfuss/00_Dev/authjs-nuxt-new/node_modules/.pnpm/h3@1.7.1/node_modules/h3/dist/index.mjs:1359:7)
playground_keycloak:dev: [nuxt] [request error] [unhandled] [500] event.node.res.appendHeader is not a function
```

**Comment by Hebilicious** [comment]
`appendHeadear` is a node.js utility.

Which version of node.js are you using ?

**Comment by dissy123** [comment]
thank you works with upgrading the node version!
